# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mustapha <mustapha@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/03/29 17:58:45 by mustapha          #+#    #+#              #
#    Updated: 2022/03/29 18:01:21 by mustapha         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = isBrain

SRC =  main.cpp

all : $(NAME)

$(NAME): $(SRC)
	@c++  $(SRC) -o $(NAME)

clean:
	@rm -rf $(NAME)

fclean:
	@rm -rf $(NAME)

re: fclean all